%% fNIRS PLV Group-Level Statistics
% Independent-samples t-tests comparing PLV matrices
% between young and old groups, with FDR correction.

clear; clc; close all;

%% Load PLV matrices for young and old groups
% These .mat files should be generated by fNIRS_PLV_calculation.m
load('PLVmatrix_resting_young.mat'); % variable: plv_oxy_young (ch * ch * sub)
load('PLVmatrix_resting_old.mat');   % variable: plv_oxy_old   (ch * ch * sub)

nChannels = size(plv_oxy_young,1);

%% Initialize p-value matrix
% Start with all ones so that diagonal entries (i==j) are excluded
p_values = ones(nChannels, nChannels);

%% Run independent-samples t-tests
for i = 1:nChannels
    for j = 1:nChannels
        if i ~= j
            y_data = squeeze(plv_oxy_young(i,j,:));
            o_data = squeeze(plv_oxy_old(i,j,:));
            [~, p_values(i,j)] = ttest2(y_data, o_data);
        end
    end
end

%% FDR correction across all pairwise connections
% Flatten matrix, apply correction, then reshape back
p_vec = p_values(:);
[h_fdr, crit_p, ~, adj_p] = fdr_bh(p_vec); % requires fdr_bh.m in the path
p_fdr = reshape(adj_p, nChannels, nChannels);

%% Save results
save('PLV_statistics_results.mat', 'p_values', 'p_fdr');

%% Display summary
fprintf('Number of significant edges (FDR corrected, p<0.05): %d\n', sum(h_fdr));
